version: '3.4'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
      - '9005:9005'
    environment:
      PHP_ENABLE_XDEBUG: 1
    networks:
      - memadnet
  db:
    image: mariadb:10.4.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=memad
      - MYSQL_USER=memad
      - MYSQL_PASSWORD=memad
    volumes:
      - memad-db:/var/lib/mysql
    networks:
      - memadnet
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=memad
      - MYSQL_USER=memad
      - MYSQL_PASSWORD=memad
    ports:
      - 8080:80
    networks:
      - memadnet
networks:
  memadnet:
volumes:
  memad-db:
